# Generated by Django 4.2.1 on 2023-08-31 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_customuser_secret_backupcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcodes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
