# Generated by Django 4.2.1 on 2023-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_alter_backupcodes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='secret',
            field=models.CharField(max_length=128, verbose_name='secret'),
        ),
    ]
