# Generated by Django 4.2.1 on 2023-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_alter_customuser_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcodes',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
