# Generated by Django 4.2.4 on 2023-09-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0007_alter_backupcodes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='TOTP',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
