# Generated by Django 4.2.4 on 2023-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0008_customuser_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='TOTP',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
