# Generated by Django 4.2.4 on 2023-09-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0009_alter_customuser_totp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='TOTP',
        ),
    ]
